# ===================
# ====== task ======
# ===================
task_set: "webshop" # "general" or "webshop"
task_split: "train" # "train" or "test"
eval_sample_mode: "random" # "random" or "sequential"
# max_steps of AitW General should be 10; of AitW Web Shopping should
max_steps: 20

# ===================
# ====== token ======
# ===================
huggingface_token: ''
wandb_key: ''
gemini_key: ''

# ===================
# ====== algo ======
# ===================
policy_lm: '/root/Auto-UI-Base' # if using conda, change policy_lm to your own path
critic_lm: 'roberta-base'
capacity: 2000 # replay buffer size
epochs: 5 # number of epochs for the critic each witeration
batch_size: 4
bsize: 4 # number of emulators parallelly on the machine
rollout_size: 16 # how many trajectories to collect between training iterations (should be multiple of bsize)
grad_accum_steps: 32
warmup_iter: 0 # how many iterations to only collect data and evaluate before training
actor_epochs: 20 # number of epochs for training the actor each iteration
trajectory_critic_epochs: 5
lm_lr: 1e-4
critic_lr: 1e-4
max_grad_norm: 0.01
gamma: 0.5
seed: 0

# ===================
# ====== agent ======
# ===================
use_lora: False
agent_name: "autoui" # "autoui" or "cogagent" >>> the eval method must be "autoui" if train_algorithm is not none <<<
do_sample: True
temperature: 1.0
tau: 0.01 #soft update parameter
max_new_tokens: 128

# ===================
# ====== causal ======
# ===================
use_entropy: False
use_causal: False
entropy_coeff: 1.0
causal_lr: 1e-5
causal_pretrain: 500
causal_epochs: 2

# ===================
# ====== log ======
# ===================
record: False # whether you want to record mp4 videos
use_wandb: True
entity_name: ''
project_name: ''

# ===================
# ====== path ======
# ===================
# query by: echo $ANDROID_AVD_HOME
android_avd_home: '~/.android/avd'
# query by: which emulator
emulator_path: '~/.android/emulator/emulator'
# query by: which adb
adb_path: '~/.android/platform-tools/adb'
cache_dir: '/root/.cache' # if using conda, change cache_dir to your own path
assets_path: '<repo_path>/CoSo/digirl/environment/android/assets/task_set'
