defaults:
  - default
  - _self_

save_path: './logs/CoSo-webshop-offline/'
run_name: 'CoSo-webshop-offline'

# training
train_algorithm: "digirl" # "digirl" or "filteredbc"
train_mode: "offline" # "offline" or "online" or "off2on"
task_mode: "train" # "train" or "evaluate" - "train" will do training when evaluating, "evaluate" will NOT do training
parallel: "single" # "single" or "host" or "worker"

# offline config, uncomment offline_data_path as long as train_model is offline or off2on
offline_data_path: "/root/data/webshop-off2on-sft-trajectories.pt"
offline_actor_iterations: 30
offline_critic_iterations: 20
offline_trajectory_critic_iterations: 20

train_iterations: 0
eval_iterations: 1000
save_freq: 3
